export const primaryBg      = '#1F01B9'
export const primaryText    = '#fff'
export const secondaryBg    = '#eff6ff'
export const secondaryText  = '#1F01B9'
export const themeBg        = '#e5e5e5'
export const themeText      = '#000'
export const green          = '#00802b'
export const grey          = '#737373'